In [1]:
from sqlalchemy import create_engine, inspect, text
import pandas as pd

# Connect to Database
engine = create_engine(f"mysql+pymysql://ndadmin:ndADMIN%402025@localhost:3306/deidentified_oct")
# engine = create_engine(f"mysql+pymysql://ndadmin:ndADMIN%402025@localhost:3306/mobiledoc_staging_1d_deidentified")

In [2]:
# Get Table Statistics (Row Count, Column Count)
inspector = inspect(engine)
tables = inspector.get_table_names()
stats = []

with engine.connect() as connection:
    for table in tables:
        # Get Row Count
        row_count_query = text(f"SELECT COUNT(*) AS row_count FROM `{table}`")
        row_count = connection.execute(row_count_query).scalar()

        # Get Column Count
        columns = inspector.get_columns(table)
        column_count = len(columns)

        stats.append({"table_name": table, "row_count": row_count, "column_count": column_count})

df = pd.DataFrame(stats)
df.shape

(8958, 3)

In [3]:
df.head()

                 table_name  row_count  column_count
0           _users_05112019          0            64
1                  abncodes          0             5
2              abnicdcptmap          0             8
3                abnoptions          0             3
4  abs_session_timeout_logs         62             8

In [11]:
df[df['row_count'] > 0]
# df[df['table_name'] == 'prisma_ccd_document_section']
# .to_csv("cdc_tables.csv", index=False)

                             table_name  row_count  column_count
4              abs_session_timeout_logs         62             8
8                      ACCESSDENIEDLOGS       5646            11
12          accounts_assignedto_history      20548            19
74                 actiontypeFavourites        178             8
75    activemq_interop_listener_details          1             7
...                                 ...        ...           ...
8934                             x12ebs    1159527            33
8939                           x270_cfg         13            45
8943                    x271respDetails     436459           130
8946                 X271TransErrorLogs      87099            17
8955                           zipcodes         56            11

[926 rows x 3 columns]

In [5]:
df['row_count'].describe()

count    8.958000e+03
mean     2.360233e+04
std      5.746072e+05
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.431863e+07
Name: row_count, dtype: float64

In [7]:
tables = list(df[df['row_count'] > 0]['table_name'])
len(tables)

926

<h1>Data Merge QC</h1>

In [8]:
from sqlalchemy import create_engine, inspect, text
import pandas as pd

# Connect to Database
engine = create_engine(f"mysql+pymysql://ndadmin:ndADMIN%402025@localhost:3306/deidentified_oct")

In [10]:
# Get Table Statistics (Row Count, Column Count)
inspector = inspect(engine)
stats = []

with engine.connect() as connection:
    for table in tables:
        # Get Row Count
        row_count_query = text(f"SELECT COUNT(*) AS row_count FROM `{table}` WHERE nd_operation IS NOT NULL")
        try:
            row_count = connection.execute(row_count_query).scalar()

            # Get Column Count
            columns = inspector.get_columns(table)
            column_count = len(columns)
        except:
            row_count = None
            column_count = None

        stats.append({"table_name": table, "row_count": row_count, "column_count": column_count})

prod_df = pd.DataFrame(stats)
prod_df.shape

(280, 3)

In [14]:
prod_df

                      table_name  row_count  column_count
0    accounts_assignedto_history        NaN           NaN
1                 addressmanager        NaN           NaN
2              AdjustmentPosting        NaN           NaN
3                      alertdata        NaN           NaN
4               alertdata_status        NaN           NaN
..                           ...        ...           ...
275                 voicemsglogs        NaN           NaN
276             voiceptmsgconfig        NaN           NaN
277                       x12ebs        NaN           NaN
278              x271respDetails        NaN           NaN
279           X271TransErrorLogs        NaN           NaN

[280 rows x 3 columns]

In [15]:
final = df.merge(prod_df, on=['table_name', 'row_count', 'column_count'], how='inner')
final.shape

(34, 3)

In [16]:
final

             table_name  row_count  column_count
0             allergies         50            18
1           annualnotes        844             8
2           billingdata        427            38
3           edi_inv_cpt       8771           111
4     edi_inv_diagnosis          5            16
5           edi_invoice       3998           108
6                   enc       1212            95
7          encaddendums          3            11
8         encounterData       4574            69
9            encounters        193            16
10               family        128            10
11     hl7labdatadetail      10128            25
12          hl7labnotes      11516            12
13                  hpi        214            14
14     InteractionNotes         10            10
15              labdata        956            75
16            labdataex        636            40
17                Notes        270            10
18          OldRxDetail       2168             7
19            OldRxMain        528            37
20   oldrxmain_addlinfo        198            17
21             patients       1068           142
22         procedurespl         85            12
23        ptinstruction          1             8
24               review        284            11
25  Rx_Medication_Alert          6            20
26               social        698            10
27  structSocialHistory        119            15
28      structured_data         34            13
29      surgicalhistory        116            10
30               telenc        348            25
31       treatmentnotes         13             8
32                users       1017            95
33        vitalshistory        252            18