In [1]:
from sqlalchemy import create_engine, text
import pandas as pd

source_engine = create_engine("mysql+pymysql://ndadmin:ndADMIN%402025@172.30.0.209:3306/dent_emd_serono")

patients_df = pd.read_csv("/Users/ndaidcnd/Desktop/Soorykant/Biohaven/parkinson_patient_list.csv")
patients = tuple(set(patients_df['patientid'].to_list()))
len(patients)

6330

In [2]:
enc_df = pd.read_sql(text(f"select patientId, encounterID from enc where patientId in {patients}"), source_engine.connect())
enc_df.shape

(393294, 2)

In [3]:
enc_df.head()

   patientId  encounterID
0      95390        61386
1      95390        86861
2      95390       161340
3      95390       175373
4      95390       257234

In [4]:
encounter_counts = enc_df.groupby('patientId')['encounterID'].count().reset_index()
encounter_counts.rename(columns={'encounterID': 'encounter_count'}, inplace=True)
encounter_counts = encounter_counts.sort_values(by='encounter_count', ascending=False)
encounter_counts

      patientId  encounter_count
2124     204404             1119
661      116598              909
2288     213628              813
1053     137934              780
247      101921              683
...         ...              ...
1106     141706                1
4023     336482                1
1437     162735                1
616      113147                1
1878     189747                1

[6330 rows x 2 columns]

In [5]:
encounter_counts[encounter_counts['encounter_count']>200]

      patientId  encounter_count
2124     204404             1119
661      116598              909
2288     213628              813
1053     137934              780
247      101921              683
...         ...              ...
2061     200232              202
2312     215335              202
2858     252969              202
313      103405              201
4371     368469              201

[316 rows x 2 columns]

In [6]:
sum(encounter_counts[encounter_counts['encounter_count']>200]['encounter_count'])

98727

In [ ]:
enc_df['patientId'].nunique(), enc_df['encounterID'].nunique()p

(6330, 393294)

In [8]:
enc_df.to_csv("/Users/ndaidcnd/Desktop/Soorykant/Biohaven/patient_enc_list.csv", index=False)